version: '3.3'
services:
  db:
    image:
      nouchka/sqlite3:latest
    volumes:
      - ./paintproject:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: ./paintproject
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./paintproject:/code
    ports:
      - "8000:8000"
    depends_on:
      - db